---
title: "Development notes"
author: "Ying Jin"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Visualization methods 

##  Dynamic MDS

In real dataset, because of the presence of missing value (all missing or missing complete pairs), some correlation measure cannot be calculated at some time slices. In such scenarios, Dynamic penalization become possible, because it is not possible to calculate the difference between configuration. 

We could potentially calculate the difference of nodes that exist in both slices. 

For "empty slices", where no data is available for plot, we could skip this slide and penalize the difference between the two adjacent non-empty slices instead. 

## Splines MDS

- The time may not be a regular grid. For Spline basis, we cannot use time index. We need to use the original time grid
- How to initialize layout, since the first slice may have missing variables
- For sub network plot, what if all of the variables selected are missing? It's gonna through error.

# App improvments

1. Automatically create time index
2. Variable and time slice summary on first page
3. Reduce time for computation
4. normalization:  How to standardize longitudinal data? 
5: Summary: how to summary longtiudinal/non-longitudinal variables? 

6: Make the size of nodes change with numeric values? 
    Can't really do that because the node represent variables, instead of a specific value. In fact, one node represents a vector of the same variable of all subjects in the sample at a specific time point. 
    
6. For now all the variables are still assumed to be numeric. What if we would like to include categorical variables
  - What type of correlation? How to code the values?
  - How to write 
  
# Journal

[Journal of statistical software](https://www.jstatsoft.org/mission)

- Case study
- Reproducible code
- Comparison to existing implementations
- Shiny app alone may not be adequate. A package is needed. 
  - stable version and developing version 